using System;
using System.Collections.Generic;
using System.Text;

namespace EJ3
{
    public class Facade
    {

    }
}
//LLEVA SOLO LOS MÉTODOS QUE REPRESENTAN LAS OPERACIONES DEL SISTEMA
//DEBO INGRESAR SOLAMENTE LOS DATOS PRIMITIVOS COMO PARÁMETROS (QUE PROVIENEN DESDE LA INTERFAZ)
//DENTRO DEL MÉTODO DE FACHADA CREAR LOS OBJETOS QUE INTERACTÚEN ENTRE SI
//Y LUEGO DEVOLVER LA INFORMACIÓN